### ISSUE TITLE
Disabling logging

### ISSUE THREAD

**Issue by RobinvanderVliet** [ical4j/ical4j#151]
Is it possible to disable debug logging with a certain function or a properties file? Currently debug logging of ical4j is spamming our log file.

I found the following code in the project, but I couldn't find a way to actually disable it:
```
if (log.isDebugEnabled()) {
    log.debug("Parameter [" + paramName + "]");
}
```

**Comment by benfortuna** [comment]
The logs in ical4j use the slf4j logging API, so it will depend what logging implementation you have in your classpath.

If you use log4j or logback you will find some sample config files in the src/test/resources directory of this project.

Otherwise you'll find the best information on the slf4j website.
