### ISSUE TITLE
CalculateRecurrenceSet bug with timeZone and all-day event.

### ISSUE THREAD

**Issue by xingmarc** [ical4j/ical4j#247]
**Describe the bug**
component#calculateRecurrenceSet is not giving the correct recurrence set on some of the time zone.

**To Reproduce**

```
    @Test(groups = { "unit" })
    public void t() throws ParseException, SocketException {
        net.fortuna.ical4j.model.Date dtStart = new net.fortuna.ical4j.model.Date("20180601");
        // All day event on 2018-06-01
        net.fortuna.ical4j.model.component.VEvent vEvent = new net.fortuna.ical4j.model.component.VEvent(dtStart, "Test Event");
        net.fortuna.ical4j.util.UidGenerator ug = new net.fortuna.ical4j.util.FixedUidGenerator("1");
        vEvent.getProperties().add(ug.generateUid());
        // Recurrence Rule Monthly.
        vEvent.getProperties().add(new net.fortuna.ical4j.model.property.RRule("FREQ=MONTHLY;INTERVAL=1"));
        System.out.println(vEvent);
        net.fortuna.ical4j.model.TimeZoneRegistry registry = net.fortuna.ical4j.model.TimeZoneRegistryFactory.getInstance().createRegistry();
        net.fortuna.ical4j.model.TimeZone tz = registry.getTimeZone("America/Los_Angeles");
        net.fortuna.ical4j.model.DateTime p1 = new net.fortuna.ical4j.model.DateTime("20180630T170001", tz);
        net.fortuna.ical4j.model.DateTime p2 = new net.fortuna.ical4j.model.DateTime("20180804T000000", tz);

        // Calculate recurrence Set on time range p1 and p2
        System.out.println(vEvent.calculateRecurrenceSet(new net.fortuna.ical4j.model.Period(p1, p2)));
        // prints 20180801T000000Z/PT0S
        // should have another recurrence on 20180701
        // Expected result should be 20180701T000000Z/PT0S,20180801T000000Z/PT0S
        // if change the start time to any time before 20180630T170000, then the result set contains 
        // 20180701
    }
```

**Environment (please complete the following information):**
 - OS: Linux RHEL 6
 - Java Version 8
 - ical4j version 2.2.o

**Comment by benfortuna** [comment]
I think this is a symptom of how we currently implement all-day events in iCal4j. Because net.fortuna.ical4j.model.Date is a subclass of java.util.Date, it must have an associated timezone.

The default timezone is UTC, primarily because there are no daylight savings rules that may affect the date value.

However it does mean that in some cases such as calculating recurrence sets, it can generate incorrect results.

You can override the behaviour such that the local timezone will be used for all-day events by adding a configuration property as follows:

`net.fortuna.ical4j.timezone.date.floating=true`

Just be aware that this may also product incorrect results when calculating in daylight savings date ranges.

In future we hope to migrate to the new Java date/time API which should correct this issue.

**Comment by xingmarc** [comment]
👍 Thank you for your quick response! @benfortuna

**Comment by derTobsch** [comment]
Is there anything new to this issue? I think I run into it in the 4.x

**Comment by benfortuna** [comment]
The implementation in 4.x is very different, I would suggest raising a new issue with an example of the code and result you are seeing.

**Comment by benfortuna** [comment]
Closing this issue as ical4j 4.0 has been released with new Java date/time API support. For related issues with 4.x pls open a new issue.

**Comment by derTobsch** [comment]
@benfortuna can you guide me to an example with floating dates with LocalDate?
