### ISSUE TITLE
JSR-310: API breakage

### ISSUE THREAD

**Issue by mwkroening** [ical4j/ical4j#399]
When using a library with a dependency on v3 and overriding this to v4, the library does not work anymore, as it was compiled against the older API.

What is your plan regarding this API breakage? Do we first have to make sure, all dependencies are upgraded to v4? Or would it be better to publish v4 with different name and packages?

Personally I would be fine with both.

**Comment by benfortuna** [comment]
Yes the API breakage is unavoidable due to the fundamental differences in the old/new Java date/time APIs.

I would prefer to continue publishing under the same package name (ical4j) as the intention is ultimately to migrate to the new APIs, however this may not be feasible for large codebases and so we'll continue to support the old version for a while (likely just patching and bug fixing).

We try to follow semantic versioning (roughly) so the major version change (4.x) indicates API breakage, although this will be the biggest change in the history of the package. It may take some time to see how well the new APIs are received.

**Comment by mwkroening** [comment]
All right. Thanks for the quick reply!
