### ISSUE TITLE
OSGI service loader resolution should be optional

### ISSUE THREAD

**Issue by ky940819** [ical4j/ical4j#405]
Perhaps I am missing something, and someone with more experience interweaving java service loader and OSGI can explain why this resolution is not optional:

https://github.com/ical4j/ical4j/blob/9b82efeb7dc5ff0d2df238114225d157009ce96d/bnd.bnd#L3

It seems to me that this bundle is the bundle that is going to provide services under the package net.fortuna.ical4j.model.*

What I am experiencing is that the services are not registered until the bundle starts, and the bundle can't start until something satisfies the requirement.

My testing shows that the bundle starts fine in an OSGI environment if ";resolution:=optional" is added to the end. E.g.:
` Require-Capability: osgi.extender;filter:="(osgi.extender=osgi.serviceloader.processor)", osgi.serviceloader;filter:="(osgi.serviceloader=net.fortuna.ical4j.model.*)";cardinality:=multiple;resolution=optional 
`

Additionally, the bundle starts fine if I use another bundle to register something useless under that package name; thus satisfying the requirement.

I believe making the resolution optional makes sense because this bundle doesn't actually require another bundle to make the services available; however as per the [spec](https://osgi.org/specification/osgi.cmpn/7.0.0/service.loader.html#d0e106792), services provided by a different bundle under that namespace would still be visible to this bundle.

This is a fairly trivial non-breaking change, but would allow us to continue using this project, and it would be greatly appreciated if someone could consider this.

**Comment by benfortuna** [comment]
Hi, yes I finally got around to testing in an OSGi environment recently and found the service loader directive was failing.

I have applied the optional resolution you suggested, so let me know if the latest release works for you.

**Comment by viliusz** [comment]
Considering this issue is still open and relevant, hence posting here.

In most recent release version (3.0.20) MANIFEST.MF file has `resolution=optional` where it should be `resolution:=optional` (notice missing `:` (colon) after `resolution`).

Repackaging jar with updated MANIFEST.MF will remove errors from logs when loading.

**Comment by kriegfrj** [comment]
I've just gotten back to iCal4J and I'm using OSGi. A couple of thoughts on this ticket:

1. The "resolution=optional" directive has not been properly implemented. I'm informed by @bjhargrave (CTO of OSGi Alliance) that it should be "resolution:=optional" is the correct way to do it.
2. More importantly, I think that optional resolution is not the best way to solve this issue. Services in this package are not optional for iCal4J to work; it's just that iCal4J itself provides default implementations. It would be more appropriate for iCal4J to declare these implementations in its manifest using a series of Provide-Capability statements.

the most appropriate way to do this not through making it optional, but for the ical4j to declare its own capability

> Considering this issue is still open and relevant, hence posting here.
> 
> In most recent release version (3.0.20) MANIFEST.MF file has `resolution=optional` where it should be `resolution:=optional` (notice missing `:` (colon) after `resolution`).
> 
> Repackaging jar with updated MANIFEST.MF will remove errors from logs when loading.

I just recently got back into iCal4J and I'm in an OSGi environment - I hit this exact same issue.

However, upon examining it further, I'm not sure if optional resolution is even the best solution to this problem. The services in question are actually required for iCal4J to work - they are not optional. It's just that iCal4J itself provides default implementations so that the requirements are always satisfied. It would be a neater solution (I think) if iCal4J declared `Provide-Capability` directives for the default implementations, rather than declare the requirement to be optional. That way the resolver knows that the default is available.

**Comment by kriegfrj** [comment]
> However, upon examining it further, I'm not sure if optional resolution is even the best solution to this problem. The services in question are actually required for iCal4J to work - they are not optional. It's just that iCal4J itself provides default implementations so that the requirements are always satisfied. It would be a neater solution (I think) if iCal4J declared `Provide-Capability` directives for the default implementations, rather than declare the requirement to be optional. That way the resolver knows that the default is available.

Another 24 hours and I'm not sure I got the above part right. But definitely fixing the "resolution:=optional" would be great.

**Comment by benfortuna** [comment]
Ok I've submitted a PR to fix the typo

**Comment by benfortuna** [comment]
Fix included in 3.0.21 release: https://search.maven.org/artifact/org.mnode.ical4j/ical4j/3.0.21/jar
