### ISSUE TITLE
iCal4j Only supported RFC 2445? iCal4j not RFC 5545 support?

### ISSUE THREAD

**Issue by dongmin-shin** [ical4j/ical4j#46]
When I don't know RFC 5545, I'm using only iCal4j (implement RFC 2445)
but I find RFC 5545 and I wonder if ical4j supports RFC5545.

If iCal4j not support RFC 5545, What is difference between RFC2445 and RFC5545?

**Comment by benfortuna** [comment]
Hi,

Rfc5545 is essentially a refresh of the rfc2445 specification. As such,
ical4j should support most of the rfc5545 specification, although I haven't
verified it against the entire specification.

If you happen to find something where ical4j doesn't conform to rfc5545 do
let me know by raising a new issue in github.

Regards,
Ben

Ps. I don't have a definitive list of differences between the two
specifications, but I suspect most changes are intended to remove ambiguity
and increase coherence of the specification, rather than any major breaking
changes.

**Comment by dongmin-shin** [comment]
Thank you Ben :)
