### ISSUE TITLE
Return an immutable collection for convenience methods getAlarms etc

### ISSUE THREAD

**Issue by douglm** [ical4j/ical4j#525]
**Describe the bug**
Now we can have multiple component typesin an entity, e.g. alarms, vlocations and participants for an event, voters and candidates for vpoll.

getVoters() provides a filtered view of the list of components - something like getVoters().add(<newvoter>) doesn't work because it's added to the filtered result - not the components.

**To Reproduce**
Have code using the dev version that does the above.

**Expected behavior**
The added voter should appear in the list. There's a number of fixes - getComponents().add(...) would work.

Returning some form of Collection implementation might also work - it has the nice feature that it would work for any component type - i.e get(1) would return the first matching, clear would clear only the matching etc.
 
In the short term at least having getComponents(final String name) return an immutable list guards against problems

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Linux, Android]
 - Java Version [e.g. 7, 8, 9]

**Additional context**

**Comment by douglm** [comment]
I think - unless we can manufacture an immutable ComponentList - that we should change the return type of getComponents(name) to be List<>.

**Comment by benfortuna** [comment]
Immutable collections as return values is one of the changes added to the ical4j 4.x branch, as part of the functional programming improvements:

http://ical4j.github.io/2020/06/21/functional-programming.html

I have avoided this change in ical4j 3.x due to compatibility issues, but I think we can return immutable lists (using generic `List<E>` signature) without breaking too much code.

I've made changes in the develop branch for this, will be included in the next 3.x release.
