### ISSUE TITLE
Some VTimezone ics files don't match between fileName and Tzid.

### ISSUE THREAD

**Issue by seungyeonchoi** [ical4j/ical4j#594]
**Describe the bug**
Some VTimezone ics files don't match between fileName and Tzid

```
Bamako.ics
Libreville.ics
Guernsey.ics
Niamey.ics
Isle_of_Man.ics
Godthab.ics
```

ex)convert string to DtStart ical4j object
DTSTART;TZID=America/Godthab:20090814T110000 -> DTSTART;TZID=America/Nuuk:20090814T110000

**To Reproduce**
N/A

**Expected behavior**
I want to know the background of this change. What time zone information did you refer to?! Please let me know the reason if it is not bug. thanks!

**Screenshots**
ex1) Bamako.ics -> Africa/Abidjan
![image](https://user-images.githubusercontent.com/48347010/186885334-7459056c-f32a-477f-85b7-001448b20894.png)

ex2)Libreville.ics ->  Africa/Lagos
<img src = "https://user-images.githubusercontent.com/48347010/186884648-b50f706a-5cdc-444d-ab3d-3063382e388c.png" width = "450" />

**Environment (please complete the following information):**
- OS: MacOS
- Java Version 1.8
- ical4j version: 3.1.1
- ical4j-zoneinfo-outlook version: 2.1.2

**Additional context**

**Comment by benfortuna** [comment]
The decision on Timezone names is managed by the IETF governing body for timezone data. You can see some of the naming decision in the wiki page:

https://en.wikipedia.org/wiki/Tz_database#Location

Ultimately there is a long and complicated history of timezone name changes, sometimes due to consolidation (when it is determined the timezones are similar enough to be merged), sometimes spelling changes, etc. 

When there is a name change it is common to create an alias from the old name to the new name, and in the iCal4j zoneinfo, for simplicity, we currently use this info to generate a separate file with the same content.
