### ISSUE TITLE
Are there any plans to release version without `jool-java-8`?

### ISSUE THREAD

**Issue by solomax** [ical4j/ical4j#626]
In our project Apache OpenMeetings we are using ical4j to create *.ics attachments for calendar reminder
Everything work as expected
Thanks a lot for the great library :))

I'm trying to keep all plugins and dependencies at their latest version
And recently got build failed during javadoc phase

The trouble-maker was `jool-java-8` library which has no "Automatic-Module-Name" and auto-module-name-creation failed for this library

The details are here:
https://lists.apache.org/thread/5twhz7mnwl0jc4vzvpsnm77lm6tjwf9q

Maybe you can release the version of ical4j without this dependency?
(As I understand `develop` branch doesn't have this dependency)

Thanks in advance! :))

**Comment by benfortuna** [comment]
Hi, thanks for asking.

We added jool to handle checked exceptions in lambda functions in the copy method of Calendar and Component. However since then we refactored away from checked exceptions, so I don't believe we need it anymore.

I've just committed the change to remove the jool dependency, and will be included in the next 4.0 beta release.

**Comment by solomax** [comment]
Thanks a million!
